// Auto-generated by scripts/generate-bindings.ts.
//
// This is a fallback stub committed so `tsc` succeeds before the contract is
// deployed. Running `pnpm bindings:generate` after `pnpm contracts:deploy`
// overwrites this file with the real method list pulled from
// `stellar contract bindings json`.
//
// Source: stellar_payment_gateway_escrow
export const METHOD_NAMES = [] as const;
export type MethodName = (typeof METHOD_NAMES)[number];
