// Root ESLint v9 flat config for the Stellar Payment Gateway polyrepo.
//
// ESLint v9 dropped legacy `.eslintrc` autoload — every package that runs
// `eslint src` needs a flat config. The shared presets in
// `packages/eslint-config/` already emit flat-config arrays (post the
// typescript-eslint umbrella switch), so we just `import` them and spread
// them into the root array. No `FlatCompat` / `@eslint/eslintrc` needed.
//
// `next lint` (apps/web) and direct `eslint src` invocations from each
// package walk up to this file from their CWD and merge the config.

import reactConfig from './packages/eslint-config/react.js';
import nodeConfig from './packages/eslint-config/node.js';

export default [
  {
    // Build artefacts, dependencies, generated bindings, and Rust target
    // output are out of scope. Mirrors the ignores list in
    // `apps/web/eslint.config.js`.
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/build/**',
      '**/target/**',
      '**/coverage/**',
      '**/.turbo/**',
      '**/*.wasm',
      // Generated TS bindings — regenerated by `pnpm bindings:generate`
      // and would generate chore-level churn in lint output.
      'packages/soroban-client/src/bindings/**',
    ],
  },
  ...reactConfig,
  ...nodeConfig,
];
