#!/usr/bin/env tsx
/**
 * Generate TypeScript bindings into `packages/soroban-client`.
 *
 * Output layout:
 *   packages/soroban-client/src/bindings/
 *     bridge.ts
 *     factory.ts
 *     wrapper-token.ts
 *   packages/soroban-client/src/index.ts        // written only if absent
 *
 * This script is a thin wrapper around `stellar contract bindings json`.
 */

import { spawn } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(__dirname, '..');
const out = resolve(root, 'packages/soroban-client/src/bindings');
const indexPath = resolve(root, 'packages/soroban-client/src/index.ts');

mkdirSync(out, { recursive: true });

const targets: Array<{ alias: string; file: string }> = [
  { alias: 'stellardao_bridge', file: 'bridge.ts' },
  { alias: 'stellardao_factory', file: 'factory.ts' },
  { alias: 'stellardao_wrapper_token_template', file: 'wrapper-token.ts' },
];

// Fallback stub written when `stellar contract bindings json` cannot be
// reached (no deployed contract, no stellar CLI on PATH, sandboxed CI, etc.).
// The real generator is the only authoritative source; this stub exists
// purely so the TypeScript barrel's `export { ... }` lines resolve.
const stubShim = (alias: string): string =>
  `// Auto-generated by scripts/generate-bindings.ts.\n` +
  `// Source: ${alias}\n` +
  `// FALLBACK stub — overwritten on the next successful run after\n` +
  `// \`pnpm contracts:deploy\`.\n` +
  `export const METHOD_NAMES = [] as const;\n` +
  `export type MethodName = (typeof METHOD_NAMES)[number];\n`;

const run = (cmd: string, args: string[]) =>
  new Promise<string>((res, rej) => {
    let out = '';
    const c = spawn(cmd, args, { cwd: root });
    c.stdout?.on('data', (d) => (out += d.toString()));
    c.on('close', (code) => (code === 0 ? res(out) : rej(new Error(`exit ${code} for ${cmd} ${args.join(' ')}`))));
  });

const main = async () => {
  for (const target of targets) {
    try {
      const json = await run('stellar', [
        'contract',
        'bindings',
        'json',
        '--alias',
        target.alias,
      ]);
      /** @type {Record<string, unknown>} */
      const parsed = JSON.parse(json);
      // Provide a tiny TS shim that re-exports the methods so consumers don't
      // need to import the raw schema.
      const fnNames = parsed.methods?.map((m: { name: string }) => m.name) ?? [];
      const shim = `// Auto-generated by scripts/generate-bindings.ts.\n` +
        `// Source: ${target.alias}\n` +
        (fnNames.length
          ? `export const METHOD_NAMES = ${JSON.stringify(fnNames)} as const;\n` +
            `export type MethodName = (typeof METHOD_NAMES)[number];\n`
          : '');
      writeFileSync(resolve(out, target.file), shim);
      console.log('[bindings] wrote', target.file, `(${fnNames.length} methods)`);
    } catch (err) {
      // Always write *something* — even if the stellar CLI can't be reached,
      // the TypeScript barrel's `export * from './bindings/<name>.js'` line
      // still needs a file to resolve. The stub makes `MethodName = never`,
      // which is a valid (if useless) type for any code that imports it
      // before contracts are deployed.
      const fallbackPath = resolve(out, target.file);
      if (!existsSync(fallbackPath)) {
        writeFileSync(fallbackPath, stubShim(target.alias));
        console.warn(
          '[bindings] wrote fallback stub',
          target.file,
          '(run deploy.ts first to get real methods)',
        );
      } else {
        console.warn('[bindings] skipped', target.alias, '(leaving existing file)');
      }
    }
  }

  // Emit an index.ts barrel only when one isn't already present. Each binding
  // file exports the literal name METHOD_NAMES / type MethodName, so a plain
  // `export *` would be ambiguous (TS2308). Use prefixed aliases so consumers
  // can import the union through a single package-root entry-point without a
  // name clash between the three contracts.
  if (!existsSync(indexPath)) {
    writeFileSync(
      indexPath,
      [
        'export {',
        '  METHOD_NAMES as BRIDGE_METHOD_NAMES,',
        '  type MethodName as BridgeMethodName,',
        "} from './bridge.js';",
        '',
        'export {',
        '  METHOD_NAMES as FACTORY_METHOD_NAMES,',
        '  type MethodName as FactoryMethodName,',
        "} from './factory.js';",
        '',
        'export {',
        '  METHOD_NAMES as WRAPPER_TOKEN_METHOD_NAMES,',
        '  type MethodName as WrapperTokenMethodName,',
        "} from './wrapper-token.js';",
        '',
      ].join('\n'),
    );
    console.log('[bindings] wrote index.ts');
  }

  console.log('[bindings] done — run `cargo build --target wasm32-unknown-unknown --release` followed by `pnpm contracts:deploy` for real contracts first.');
};

main();
